---
title: "data manipulation"
author: "Xiaoyang Li"
date: "2019/9/18"
output: html_document
---
```{r set uo}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

```

## import datasets
```{r}
litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```

## selecting

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, group, litter_number, everything()) # everything

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP = group, litter_number)

rename(litters_data, GROUP = group)
```

## filtering

```{r}
filter(litters_data, group == "Con7")

filter(litters_data, gd_of_birth < 20)

filter(litters_data, pups_born_alive < 6, group == "Con7")

filter(litters_data, group == "Con7" & gd0_weight > 20)

filter(litters_data, group == "Con7" | group == "Mod8")

filter(litters_data, gd0_weight + gd18_weight < 70)

# don'tt do this
filter(litters_data, !is.na(gd0_weight))

drop_na(litters_data, gd0_weight)


```


## mutating

```{r}
mutate(litters_data, wt_gain = gd18_weight - gd0_weight)

mutate(litters_data, group = tolower(group))

mutate(litters_data, group = str_to_lower(group))

```


## arranging

```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)
```

## pipe ...

create a collection of commands

```{r}
litters_data_pipe = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)
```

```{r}
litters_data_pipe2 = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names(dat = .) %>% 
  select(.data = ., -pups_survive) %>% 
  lm(gd0_weight ~ gd18_weight, data = .)
```

